baseURL = 'https://yandextrackerproject.github.io/'
languageCode = 'ru'
title = 'Яндекс Tracker для Управления программными проектами'
theme = 'hello-friend'
[params]
  author = 'Яндекс Tracker для Управления программными проектами'
  defaultTheme = "dark"
[menu]
[[menu.main]]
  name = 'Лекции'
  pageRef = '/Лекции'
  weight = 10
[[menu.main]]
  name = 'О Проекте'
  pageRef = '/О_Проекте'
  weight = 9
[[menu.main]]
  name = 'Практики'
  pageRef = '/Практики'
  weight = 10
[[menu.main]]
  name = 'Тесты'
  pageRef = '/Тесты'
  weight = 10
[[menu.main]]
  name = 'Дополнительно'
  pageRef = '/Дополнительные_материалы'
  weight = 11
